# Generated by Django 5.2.11 on 2026-02-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
